#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/usr/nld/nrn-73"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/usr/nld/nrn-73/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/chenfei/Code_git/Models/Brette_soma20000_L2/x86_64/.libs/libnrnmech.so" "$@"
